version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: docker/go
      target: dev
    volumes:
      - .:/opt/app/api
    links:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: trip_forwarder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
volumes:
  data: